/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazgrafica;

/**
 *
 * @author bakka
 */
public class TablaUnidad extends javax.swing.JFrame {

    /**
     * Creates new form TablaUnidad
     */
    public TablaUnidad() {
        //setLocationRelativeTo(null);
        //panelUnidades.setVisible(false);
        initComponents();
        this.setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableUnidades = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tableUnidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Unidad A", "Juan Enriquez Gonalez"    , "Mercado Hidalgo", "14:15", "Base Coca", "14:02", "0 Horas, 13 Minutos","0 Horas, 15 Minutos", "2 Minutos"},
                {"Unidad B", "Luis Ojeda Ramirez"       , "Vips", "14:11", "Soriana Boulevart", "14:05", "0 Horas, 6 Minutos","0 Horas, 10 Minutos","4 Minutos"},
                {"Unidad C", "Marcos Sanchez Cruz"      , "Galerias Celaya", "14:19", "Gasolinar Eje", "14:00", "0 Horas, 19 Minutos","0 Horas, 15 Minutos","4 Minutos"},
                {"Unidad D", "Pablo Ruiz Estrada"       , "Mercado Hidalgo", "14:13", "Pepsi", "13:59", "0 Horas, 14 Minutos","0 Horas, 13 Minutos","1 Minutos"},
                {"Unidad E", "Salvador Ramirez Garcia"  , "Corona", "14:22", "Aurrera por Vias", "14:07", "0 Horas, 14 Minutos","0 Horas, 18 Minutos","4 Minutos"},
                {"Unidad F", "Jorge Luis Estrada Orozco", "Parque Celaya", "14:30","Bachoco", "14:06", "0 Horas, 24 Minutos","0 Horas, 10 Minutos","14 Minutos"},
                {"Unidad G", "Alejando Lopez Rodriguez" , "Pepsi", "14:22", "Bachoco", "14:02", "0 Horas, 20 Minutos","0 Horas, 18 Minutos","2 Minutos"}
            },
            new String [] {
                "Unidad", "Operador", "Ubicacion A", "Hora", "Ubicacion B", "Hora","Tiempo entre Ubicaciones","Promedio entre todas las rutas","Diferencia"
            }
        ));
        jScrollPane1.setViewportView(tableUnidades);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaUnidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaUnidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaUnidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaUnidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablaUnidad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableUnidades;
    // End of variables declaration//GEN-END:variables
}
